spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/store
# 修改文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

